import Head from 'next/head'
import { Inter } from '@next/font/google'
import MyPortifolio from '../components/my-portifolio'
import { GetStaticPropsResult } from 'next'
import { ProjectGithub } from '../@types/projectgithub'
import { userGithub } from '../@types/usergithub'

const inter = Inter({ subsets: ['latin'] })

type PropsHome = {
  projects: ProjectGithub[]
  user: userGithub
}

export default function Home({ projects, user }: PropsHome) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyPortifolio
        propsmain={{
          projects,
          totalProject: user.public_repos
        }}
        propsaside={{
          userGithub: user
        }} />
    </>
  )
}

export async function getStaticProps(): Promise<GetStaticPropsResult<PropsHome>> {
  const res = await fetch("https://api.github.com/users/jc-dev-stack/repos?per_page=6&page=3");
  const htt = await fetch("https://api.github.com/users/jc-dev-stack");
  const projects = await res.json();
  const user = await htt.json();
  return {
    props: {
      projects,
      user
    }, // will be passed to the page component as props
  }
}